server:
   port: 8000
#配置数据源
spring:
   datasource:
      druid:
         type: com.alibaba.druid.pool.DruidDataSource
         driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
         url: jdbc:log4jdbc:mysql://localhost:3306/une-gateway?useUnicode=true&characterEncoding=UTF-8&useSSL=false
         username: root
         password: abc123
         initial-size: 10
         min-idle: 10
         max-active: 50
         max-wait: 5000
# 连接有效性检测时间
         time-between-eviction-runs-millis: 90000
# 最大空闲时间
         min-evictable-idle-time-millis: 1800000
         test-while-idle: true
         test-on-borrow: false
         test-on-return: false
         validation-query: select 1
mybatis:
   type-aliases-package: com.vivebest.une_gateway.domain
   mapper-locations: classpath*:mybatis/mysql/*.xml